services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    command: start-dev
    ports:
      - 8080:8080
    env_file:
      - .env.keycloak
    volumes:
      - keycloak_data:/opt/keycloak/data
    restart: unless-stopped

volumes:
  keycloak_data:
